### ISSUE TITLE
[boom] str.isnumeric() is not available on Python < 3.0

### ISSUE THREAD

**Issue by bmr-cymru** [snapshotmanager/boom#8]
Lots of stuff is currently broken on the py2.7 Travis job:

```
ERROR: Test the _clone_cmd() handler with a valid entry and new
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/snapshotmanager/boom/tests/command_tests.py", line 1615, in test__clone_cmd
    r = boom.command._clone_cmd(args, None, opts, None)
  File "/home/travis/build/snapshotmanager/boom/boom/command.py", line 2095, in _clone_cmd
    (btrfs_subvol_path, btrfs_subvol_id) = _subvol_from_arg(subvol)
  File "/home/travis/build/snapshotmanager/boom/boom/command.py", line 400, in _subvol_from_arg
    subvol = parse_btrfs_subvol(subvol)
  File "/home/travis/build/snapshotmanager/boom/boom/_boom.py", line 573, in parse_btrfs_subvol
    if subvol.isnumeric():
AttributeError: 'str' object has no attribute 'isnumeric'
```

(any test that ends up calling `parse_btrfs_subvolume()` will hit this).

**Comment by bmr-cymru** [comment]
Closing this because our last Python2 distribution (RHEL7) is now in the maintenance lifecycle phase; any critical bugs can be addressed by a backport that does not include the `isnumeric()` call which cannot be required in RHEL since Btrfs is not supported.
